DROP TABLE Follows;

CREATE TABLE IF NOT EXISTS Users (
  id  VARCHAR(60) PRIMARY KEY,
  name  VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS Follows (
  follower_id VARCHAR(60) NOT NULL,
  followed_id VARCHAR(60) NOT NULL,
  friends BOOLEAN NOT NULL,

  CONSTRAINT fk1 FOREIGN KEY (follower_id) REFERENCES Users (id) ON DELETE CASCADE,
  CONSTRAINT fk2 FOREIGN KEY (followed_id) REFERENCES Users (id) ON DELETE CASCADE
);
