CREATE TABLE IF NOT EXISTS Profiles (
  id  VARCHAR(60) PRIMARY KEY,
  name  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  profile_id VARCHAR(60),

  CONSTRAINT fk1 FOREIGN KEY (profile_id) REFERENCES Profiles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Follows (
  follower_id VARCHAR(60) NOT NULL,
  followed_id VARCHAR(60) NOT NULL,
  friends BOOLEAN NOT NULL,

  CONSTRAINT fk2 FOREIGN KEY (follower_id) REFERENCES Profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk3 FOREIGN KEY (followed_id) REFERENCES Profiles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Posts (
  id VARCHAR(60) NOT NULL,
  author_id VARCHAR(60) NOT NULL,
  content VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,

  CONSTRAINT fk4 FOREIGN KEY (author_id) REFERENCES Profiles (id) ON DELETE CASCADE
);
